# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/dependent_stubgem_multiplatform.rb'

Hoe.new('dependent-stubgem-multiplatform', DependentStubgemMultiplatform::VERSION) do |p|
  p.author = 'Chad Woolley'
  p.email = 'nobody@example.com'
  p.rubyforge_name = 'dependent-stubgem-multiplatform'
  p.summary = p.paragraphs_of('README.txt', 1).first.split(/\n/)[2]
  p.description = p.paragraphs_of('README.txt', 2..5).join("\n\n")
  p.url = p.paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.spec_extras={"platform",Gem::Platform::WIN32}
  p.extra_deps=["stubgem-multiplatform",">= 1.0.0"]
end

# vim: syntax=Ruby
