# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/stubgem.rb'

Hoe.new('stubgem', Stubgem::VERSION) do |p|
  p.rubyforge_name = 'stubgem'
  # p.summary = 'FIX'
  # p.description = p.paragraphs_of('README.txt', 2..5).join("\n\n")
  # p.url = p.paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
end

# vim: syntax=Ruby
