# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/dependent_stubgem.rb'

Hoe.new('dependent-stubgem', DependentStubgem::VERSION) do |p|
  p.author = 'Chad Woolley'
  p.rubyforge_name = 'dependent-stubgem'
  p.summary = p.paragraphs_of('README.txt', 1).first.split(/\n/)[2]
  p.description = p.paragraphs_of('README.txt', 2..5).join("\n\n")
  p.url = p.paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
end

# vim: syntax=Ruby
